[package]
name = "enet-sys"
version = "0.1.4"
authors = ["Roland Ruckerbauer <roland.rucky@gmail.com>"]
description = "Low level bindings to the enet C library"
license = "MIT"
repository = "https://github.com/ruabmbua/enet-sys"
build = "src/build.rs"
links = "enet"

[dependencies]
libc = "0.2.7"
unsafe_unions = "0.0.2"
