[package]
name = "enet-sys"
version = "0.1.1"
authors = ["Roland Ruckerbauer <roland.rucky@gmail.com>"]
description = "Low level bindings to the enet C library"
license = "MIT"
repository = "https://github.com/ruabmbua/enet-sys"

build = "src/build.rs"

[dependencies]
libc = "0.2.7"
